### PR TITLE
Added parameter rollOnDateChange to AzureTableStorageSink

### PR DESCRIPTION
**Pull request by kashifsoofi**
Added parameter rollOnDateChange to AzureTableStorageSink to create a new table every day postfixed with Ticks for current date. We at WorldRemit need to pull a lot of data from log table to splunk and splunk at the moment cannot handle data once records exceed more than a million records hence need to break down the log data set.

### CODE REVIEW

**Comment by cdavid** [comment]
Hi

I like this change, but I have one comment about the pattern used - in this change you use a bool value to determine what type of ICloudTableProvider you choose. This is fine and it works right now, but the way I see this problem, I think this is a pattern that is more similar to the one used in the IKeyGenerator.

With the IKeyGenerator - we ask the user of the sink to define an interface that gives us the Partition and Row Key (and if none is provided we fall back to the default). We could have something similar in this instance where we ask the user to implement that interface. This approach would be more durable for the future, in my opinion.

Does that make sense to you? Have you thought about that? What is your opinion?

**Comment by kashifsoofi** [comment]
I completely agree with the comment. Passing ICloudTableProvider is more flexible but having the parameter makes it easy to switch on/off the rolling cloud table provider. If its alright we can open an issue to make ICloudTableProvider configurable through configuration and accepted as parameter in Sink.

**Comment by cdavid** [comment]
I am rather new here (just did my first commit a month or so ago), so pinging @nblumhardt :)

**Comment by kashifsoofi** [comment]
Closing as should be covered by similar Pull request on master.

**Pull request closed without merging**
