### PR TITLE
Fixup formatting

### PR DESCRIPTION
**Pull request by adamchester**
Replaces #18

### CODE REVIEW

**Comment by adamchester** [comment]
There should be no actual changes, only tabs->spaces, newlines, and things of that nature.

**Comment by nblumhardt** [comment]
That diff is a piece of artwork! :-D

**Comment by nblumhardt** [comment]
Looks like the build is having some issues connecting to Azure: https://ci.appveyor.com/project/serilog/serilog-sinks-azuretablestorage. Will kick it off again later to see whether it's intermittent.

**Comment by adamchester** [comment]
Yes this has already happened a few times to me; seems to go away after rebuild. I'll look into this at some point; maybe need to wait storage engine to come online

**Pull request merged**
