### PR TITLE
Allow using a SAS URL instead of the full account keys for log upload

### LINKED ISSUE #36: Allow using an SAS uri for logging purposes
I'd love to be able to restrict it so that the application only has access to a write-only SAS uri for logging purposes (so it can't tamper with or read the logs), but it appears (AFAICT) that neither `connectionString` nor the `CloudStorageAccount` support SAS uris.

### PR DESCRIPTION
**Pull request by cdavid**
Fixes #36 
Upgrades to VS 2017 + new CSPROJ (instead of XPROJ + project.json)
Upgrades to latest stable versions of dependencies

### CODE REVIEW

**Comment by cdavid** [comment]
@nblumhardt - hi, I finally got around to getting this done. I am not 100% clear on the process of merging (first commit to this project), so please advise if I did something wrong.

**Comment by nblumhardt** [comment]
Sorry about the slow turnaround; I'm not in a good position to test this currently, but the PR looks good!

I'll merge this through; if it's possible to validate the dev package that's published after the merge, feedback would be great.

Cheers!

**Comment by cdavid** [comment]
@nblumhardt - did a sanity check and all seems fine. How do we push out an official package version to Nuget?

**Comment by nblumhardt** [comment]
Thanks for looping back :-)

Normally we try to leave the pre-release package out in circulation for a little while to catch any issues that we can before pushing a "stable" package; since others will want to pick up the #36 fix it's likely we'll see a few more downloads of https://www.nuget.org/packages/Serilog.Sinks.AzureTableStorage/5.0.0-dev-00093 over the next week or two - if all is quiet then, it's a quick process to merge the changes through to master. Does this help?

Cheers,
Nick

**Comment by cdavid** [comment]
Sure this makes total sense - thanks for telling me about the policy. I also realized that I should probably update the README to contain the new usage and more info (since the SAS URL is a bit tricky - if you give it write-only permissions, the table has to exist etc.). So, I will do that and circle back in a couple of weeks.

Catalin

**Pull request merged**
