### PR TITLE
Upgrade solution for 2.0

### PR DESCRIPTION
**Pull request by adamchester**
cc @robdmoore

### CODE REVIEW

**Comment by adamchester** [comment]
Probably needs an RC first, still only net45

**Comment by nblumhardt** [comment]
Better to unblock people, let's do it :-)

**Comment by robdmoore** [comment]
Is it a problem that there are a bunch of skipped tests? Not sure if that's since been resolved :)

**Comment by adamchester** [comment]
@robdmoore yeah I think that's a problem that hasn't been fixed yet, my bad. I incorrectly assumed it wouldn't be available on AppVeyor

**Comment by robdmoore** [comment]
From memory you can define scripts to run to install stuff like that on appveyor. I haven't personally tried though.

**Pull request merged**
